version: "3.9"

networks:
  app:
    driver: bridge

services:
  db-mssql:
    container_name: db-mssql
    ports:
      - ${DB_PORT}:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${DB_PASSWORD}
    build:
      context: .docker/mssql/
      dockerfile: Dockerfile
      # args:
      #   - DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./storage/db/mssql_db/data/:/var/opt/mssql/data
    networks:
      - app